name: Deploy website on push
on: push
jobs:
  web-deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
      - uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: "[**/.**/**,  **/.git/**, README.md]"
